Remove enabling deprecated allocator members
Breaks boost::asio build with libcxx14:

In file included from /mnt/ch/ClickHouse/contrib/NuRaft/src/asio_service.cxx:28:
In file included from /mnt/ch/ClickHouse/contrib/NuRaft/include/libnuraft/asio_service.hxx:24:
In file included from /mnt/ch/ClickHouse/contrib/NuRaft/include/libnuraft/asio_service_options.hxx:20:
In file included from /mnt/ch/ClickHouse/contrib/libcxx/include/functional:506:
In file included from /mnt/ch/ClickHouse/contrib/libcxx/include/__functional/function.h:22:
In file included from /mnt/ch/ClickHouse/contrib/libcxx/include/__memory/shared_ptr.h:21:
/mnt/ch/ClickHouse/contrib/libcxx/include/__memory/allocator.h:122:44: error: cannot form a reference to 'void'
    _LIBCPP_DEPRECATED_IN_CXX17 typedef _Tp&       reference;
                                           ^
/mnt/ch/ClickHouse/contrib/boost/boost/asio/execution/any_executor.hpp:612:48: note: in instantiation of template class 'std::allocator<void>' requested here
          function(BOOST_ASIO_MOVE_CAST(F)(f), std::allocator<void>()));
                                               ^
In file included from /mnt/ch/ClickHouse/contrib/NuRaft/src/asio_service.cxx:28